# Generated by Django 4.1.1 on 2023-03-03 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cemail', models.CharField(default='', max_length=40)),
                ('cpassword', models.CharField(max_length=50)),
                ('cphone', models.CharField(max_length=12)),
                ('caddress', models.CharField(default='', max_length=40)),
                ('clocation', models.CharField(default='', max_length=20)),
                ('cpincode', models.CharField(default='', max_length=20)),
                ('cfeatures', models.CharField(default='', max_length=100)),
                ('carea', models.CharField(default='', max_length=100)),
                ('cimg', models.ImageField(default='', upload_to='images')),
                ('status', models.IntegerField(default='1')),
                ('role', models.CharField(default='company', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(default='', max_length=40)),
                ('location', models.CharField(default='', max_length=20)),
                ('pincode', models.CharField(default='', max_length=20)),
                ('status', models.IntegerField(default='1')),
                ('role', models.CharField(default='customer', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(default='', max_length=100)),
                ('companyid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.company')),
                ('userid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.customer')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='userid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.customer'),
        ),
    ]
