# Generated by Django 4.1.1 on 2023-03-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_rate_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='cemail',
        ),
        migrations.RemoveField(
            model_name='company',
            name='cpassword',
        ),
    ]
