# Generated by Django 4.1.1 on 2023-03-18 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_company_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='companyid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.company'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='userid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.customer'),
        ),
    ]
