# Generated by Django 4.1.1 on 2023-03-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_rate_companyid_alter_rate_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='crate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
