# Generated by Django 4.1.1 on 2023-03-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0026_remove_driver_offer_license'),
        ('Home', '0008_driver_job_applicatio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='driver_job_applicatio',
            new_name='driver_job_application',
        ),
    ]
