# Generated by Django 4.1.1 on 2023-03-28 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0028_alter_driver_offer_companyid_and_more'),
        ('Home', '0010_employee_job_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_job_application',
            name='companyid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.company'),
        ),
        migrations.AlterField(
            model_name='driver_job_application',
            name='jobid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Company.driver_offer'),
        ),
        migrations.AlterField(
            model_name='driver_job_application',
            name='userid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.customer'),
        ),
        migrations.AlterField(
            model_name='employee_job_application',
            name='companyid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.company'),
        ),
        migrations.AlterField(
            model_name='employee_job_application',
            name='jobid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Company.driver_offer'),
        ),
        migrations.AlterField(
            model_name='employee_job_application',
            name='userid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.customer'),
        ),
    ]
