# Generated by Django 4.1.1 on 2023-03-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_driver_job_application_companyid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.BooleanField(default='1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.BooleanField(default='1'),
        ),
    ]
