# Generated by Django 4.1.1 on 2023-03-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_alter_company_cemail_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_job_application',
            name='status',
            field=models.BooleanField(default='1'),
        ),
        migrations.AddField(
            model_name='employee_job_application',
            name='status',
            field=models.BooleanField(default='1'),
        ),
    ]
