# Generated by Django 4.1.1 on 2023-03-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_driver_job_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_job_application',
            name='review',
            field=models.BooleanField(default='0'),
        ),
        migrations.AddField(
            model_name='employee_job_application',
            name='review',
            field=models.BooleanField(default='0'),
        ),
    ]
