# Generated by Django 4.1.1 on 2023-04-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_service_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_booking',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='service_booking',
            name='pincode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='service_booking',
            name='location',
            field=models.CharField(default='', max_length=20),
        ),
    ]
