# Generated by Django 4.1.1 on 2023-04-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_service_booking_address_service_booking_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_booking',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
