# Generated by Django 4.1.1 on 2023-04-05 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_service_booking_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='dumbster_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberofdumbster', models.CharField(default='', max_length=20)),
                ('rate', models.CharField(default='', max_length=20)),
                ('size', models.CharField(default='', max_length=20)),
                ('status', models.BooleanField(default='1')),
                ('companyid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.company')),
                ('userid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.customer')),
            ],
        ),
    ]
