# Generated by Django 4.1.1 on 2023-04-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_dumbster_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dumbster_payment',
            new_name='dumbster_booking',
        ),
    ]
