# Generated by Django 4.1.1 on 2023-04-05 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0035_alter_dumbster_status'),
        ('Home', '0020_rename_dumbster_payment_dumbster_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumbster_booking',
            name='dumbsterid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Company.dumbster'),
        ),
    ]
