# Generated by Django 4.1.1 on 2023-04-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_for',
            field=models.CharField(default='', max_length=20),
        ),
    ]
