# Generated by Django 4.1.1 on 2023-04-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_alter_dumbster_booking_numberofdumbster'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumbster_booking',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
