# Generated by Django 4.1.1 on 2023-04-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0026_dumbster_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumbster_booking',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='dumbster_booking',
            name='location',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dumbster_booking',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dumbster_booking',
            name='pincode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
