# Generated by Django 4.1.1 on 2023-04-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0027_dumbster_booking_address_dumbster_booking_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_booking',
            name='rate',
            field=models.CharField(default='', max_length=20),
        ),
    ]
