# Generated by Django 4.1.1 on 2023-04-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0028_service_booking_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumbster_booking',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
