# Generated by Django 4.1.1 on 2023-04-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0029_alter_dumbster_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_booking',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
