# Generated by Django 4.1.1 on 2023-04-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0030_alter_service_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumbster_booking',
            name='expire_date',
            field=models.DateField(null=True),
        ),
    ]
