# Generated by Django 4.1.1 on 2023-04-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0032_alter_dumbster_booking_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='caddress',
            field=models.CharField(default='', max_length=140),
        ),
    ]
