# Generated by Django 4.1.1 on 2023-04-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0033_alter_company_caddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumbster_booking',
            name='arrived_near',
            field=models.BooleanField(default='0'),
        ),
        migrations.AddField(
            model_name='dumbster_booking',
            name='completed',
            field=models.BooleanField(default='0'),
        ),
        migrations.AddField(
            model_name='dumbster_booking',
            name='out_for_service',
            field=models.BooleanField(default='0'),
        ),
        migrations.AddField(
            model_name='service_booking',
            name='arrived_near',
            field=models.BooleanField(default='0'),
        ),
        migrations.AddField(
            model_name='service_booking',
            name='completed',
            field=models.BooleanField(default='0'),
        ),
        migrations.AddField(
            model_name='service_booking',
            name='out_for_service',
            field=models.BooleanField(default='0'),
        ),
    ]
