# Generated by Django 4.1.1 on 2023-04-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0034_dumbster_booking_arrived_near_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumbster_booking',
            name='status',
            field=models.BooleanField(default='0'),
        ),
    ]
