# Generated by Django 4.1.1 on 2023-05-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0035_alter_dumbster_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_job_application',
            name='phone',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='employee_job_application',
            name='phone',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
