# Generated by Django 4.1.1 on 2023-05-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0036_driver_job_application_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumbster_booking',
            name='latitude',
            field=models.CharField(default='', max_length=230, null=True),
        ),
        migrations.AddField(
            model_name='dumbster_booking',
            name='longitude',
            field=models.CharField(default='', max_length=230, null=True),
        ),
        migrations.AddField(
            model_name='service_booking',
            name='latitude',
            field=models.CharField(default='', max_length=230, null=True),
        ),
        migrations.AddField(
            model_name='service_booking',
            name='longitude',
            field=models.CharField(default='', max_length=230, null=True),
        ),
    ]
