# Generated by Django 4.1.1 on 2023-05-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0038_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='cmt',
            field=models.CharField(default='1', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
    ]
