# Generated by Django 4.1.1 on 2023-05-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0040_alter_rate_cmt'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumbster_booking',
            name='feedback',
            field=models.CharField(default='', max_length=220),
        ),
        migrations.AddField(
            model_name='service_booking',
            name='feedback',
            field=models.CharField(default='', max_length=220),
        ),
    ]
