# Generated by Django 4.1.1 on 2023-05-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0041_dumbster_booking_feedback_service_booking_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumbster_booking',
            name='feedback',
            field=models.CharField(default='', max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='service_booking',
            name='feedback',
            field=models.CharField(default='', max_length=220, null=True),
        ),
    ]
