# Generated by Django 4.1.1 on 2023-03-30 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0012_alter_company_status_alter_customer_status'),
        ('Company', '0028_alter_driver_offer_companyid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default='1', max_length=100)),
                ('companyid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.company')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.customer')),
                ('vehicle_details', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Company.vehicle')),
            ],
        ),
    ]
