# Generated by Django 4.1.1 on 2023-03-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='vehicle_details',
            new_name='vehicleid',
        ),
    ]
