# Generated by Django 4.1.1 on 2023-03-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_rename_vehicle_details_driver_vehicleid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='user_id',
            new_name='userid',
        ),
    ]
