# Generated by Django 4.1.1 on 2023-03-31 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_driver_job_application_review_and_more'),
        ('Company', '0029_alter_driver_offer_status_and_more'),
        ('Employee', '0003_rename_user_id_driver_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default='1', max_length=100)),
                ('role', models.CharField(default='', max_length=50)),
                ('companyid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.company')),
                ('userid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.customer')),
                ('vehicleid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Company.vehicle')),
            ],
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
