# Generated by Django 4.1.1 on 2023-03-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_employee_delete_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.BooleanField(default='0', max_length=100),
        ),
    ]
