# Generated by Django 4.1.1 on 2023-04-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_remove_employee_vehicleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ename',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='epass',
            field=models.CharField(default='', max_length=50),
        ),
    ]
