# Generated by Django 4.1.1 on 2023-04-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_rename_ename_employee_eemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='epass',
            new_name='epassword',
        ),
    ]
