# Generated by Django 4.1.1 on 2023-04-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_rename_epass_employee_epassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ephone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
