# Generated by Django 4.1.1 on 2023-04-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_job_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_assigned',
            name='employeeid',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='job_assigned',
            name='status',
            field=models.BooleanField(default='0'),
        ),
    ]
