# Generated by Django 4.1.1 on 2023-04-11 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0013_job_assigned_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_assigned',
            old_name='vehicle',
            new_name='vehicle_detail',
        ),
    ]
