# Generated by Django 4.1.1 on 2023-04-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0014_rename_vehicle_job_assigned_vehicle_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_assigned',
            name='assistant',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job_assigned',
            name='dumbster_scheduled',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job_assigned',
            name='service_scheduled',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job_assigned',
            name='vehicle_detail',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
