# Generated by Django 4.1.1 on 2023-04-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0016_job_assigned_date_job_assigned_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_assigned',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
