# Generated by Django 4.1.1 on 2023-04-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0019_rename_out_of_service_job_assigned_out_for_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_assigned',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='job_assigned',
            name='location',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='job_assigned',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='job_assigned',
            name='pincode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
