# Generated by Django 4.1.1 on 2023-04-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0020_job_assigned_address_job_assigned_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_assigned',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
