# Generated by Django 4.1.1 on 2023-04-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0021_alter_job_assigned_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_assigned',
            old_name='id',
            new_name='job_id',
        ),
    ]
