# Generated by Django 4.1.1 on 2023-04-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0024_leave_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
