# Generated by Django 4.1.1 on 2023-04-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0026_rename_date_leave_end_date_leave_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.BooleanField(default='1', max_length=100),
        ),
    ]
