# Generated by Django 4.1.1 on 2023-04-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0027_alter_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='role',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
