# Generated by Django 4.1.1 on 2023-04-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0029_leave_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='on_leave',
            field=models.BooleanField(default='0'),
        ),
    ]
