# Generated by Django 4.1.1 on 2023-04-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0030_employee_on_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_assigned',
            name='recollect_dumbster',
            field=models.BooleanField(default='0'),
        ),
    ]
