# Generated by Django 4.1.1 on 2023-04-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0031_job_assigned_recollect_dumbster'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_assigned',
            name='employeephone',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
