# Generated by Django 4.1.1 on 2023-05-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0032_job_assigned_employeephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_assigned',
            name='latitude',
            field=models.CharField(default='', max_length=230, null=True),
        ),
        migrations.AddField(
            model_name='job_assigned',
            name='longitude',
            field=models.CharField(default='', max_length=230, null=True),
        ),
    ]
