from django.urls import path
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', index, name='index'),
    path('login/', login, name='login'),
    path('lgout/', lgout, name='lgout'),
    path('reg/', reg, name='reg'),
    path('signup/', signup, name='signup'),
    path('signin/', signin, name='signin'),
    path('companyreg/', companyreg, name='companyreg'),
    path('companydetails/<id>', companydetails, name='companydetails'),
    path('companyrate/<id>', companyrate, name='companyrate'),
    path('jobdriverdetails/<id>', jobdriverdetails, name='jobdriverdetails'),
    path('jobemployeedetails/<id>', jobemployeedetails, name='jobemployeedetails'),
    path('applicationjobdriverpage/<id>', applicationjobdriverpage,
         name='applicationjobdriverpage'),
    path('applicationjobdriver/<id>', applicationjobdriver,
         name='applicationjobdriver'),
    path('applicationjobemployeepage/<id>', applicationjobemployeepage,
         name='applicationjobemployeepage'),
    path('applicationjobemployee/<id>', applicationjobemployee,
         name='applicationjobemployee'),
    path('jobdriverdetails_notification/<id>',
         jobdriverdetails_notification, name='jobdriverdetails_notification'),
    path('jobemployeedetails_notification/<id>',
         jobemployeedetails_notification, name='jobemployeedetails_notification'),
    path('companydetails_from_accept_notification/<str:cname>',
         companydetails_from_accept_notification, name='companydetails_from_accept_notification'),
    path('offer_accept/<str:cname>/<str:role>',
         offer_accept, name='offer_accept'),
    path('offer_deny/<str:cname>/<str:role>', offer_deny, name='offer_deny'),
    path('servicebookingpage/<str:id>',
         servicebookingpage, name='servicebookingpage'),
    path('servicebookingpaymentpage/<str:id>',
         servicebookingpaymentpage, name='servicebookingpaymentpage'),
    path('servicebooking/<id>', servicebooking, name='servicebooking'),
    path('bookdumbsterpage/<str:cname>',
         bookdumbsterpage, name='bookdumbsterpage'),
    path('bookdumbster/<str:cid>', bookdumbster, name='bookdumbster'),
    path('bookdumbsterpaymentpage/<str:cid>',
         bookdumbsterpaymentpage, name='bookdumbsterpaymentpage'),
    path('search/', search, name='search'),
    path('service_cancel/<id>', service_cancel, name='service_cancel'),
    path('tracking_page/', tracking_page, name='tracking_page'),
    path('cancel_renteddumbster/<id>', cancel_renteddumbster,
         name='cancel_renteddumbster'),
    path('employeehome/', employeehome, name='employeehome'),
    path('help_page/', help_page, name='help_page'),
    path('payment_successfull/', payment_successfull, name='payment_successfull'),
    path('dumpster_delivery_feedback/<id>', dumpster_delivery_feedback,
         name='dumpster_delivery_feedback'),
    path('service_delivery_feedback/<id>', service_delivery_feedback,
         name='service_delivery_feedback'),
]
