# Generated by Django 4.1.1 on 2023-03-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='shift_time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
