# Generated by Django 4.1.1 on 2023-03-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_job_job_type_job_shift_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vehicle_details',
            field=models.CharField(default='', max_length=100),
        ),
    ]
