# Generated by Django 4.1.1 on 2023-03-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_job_vehicle_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_title',
            field=models.CharField(default='1000', max_length=100),
        ),
    ]
