# Generated by Django 4.1.1 on 2023-03-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_job_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='shift_time',
        ),
        migrations.AddField(
            model_name='job',
            name='end_time',
            field=models.CharField(default='6:00', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='start_time',
            field=models.CharField(default='9:00', max_length=100),
        ),
    ]
