# Generated by Django 4.1.1 on 2023-03-15 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_remove_job_shift_time_job_end_time_job_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
    ]
