# Generated by Django 4.1.1 on 2023-03-15 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_company_userid'),
        ('Company', '0006_remove_job_job_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job',
            new_name='Driver',
        ),
    ]
