# Generated by Django 4.1.1 on 2023-03-15 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_rename_job_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_details',
        ),
    ]
