# Generated by Django 4.1.1 on 2023-03-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0008_remove_driver_vehicle_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='job_title',
        ),
    ]
