# Generated by Django 4.1.1 on 2023-03-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0009_remove_driver_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vehicle_details',
            field=models.CharField(default='', max_length=100),
        ),
    ]
