# Generated by Django 4.1.1 on 2023-03-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0010_driver_vehicle_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
