# Generated by Django 4.1.1 on 2023-03-16 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_company_userid'),
        ('Company', '0012_remove_driver_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(default='1000', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='1', max_length=100)),
                ('companyid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.company')),
                ('vehicle_details', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Company.driver')),
            ],
        ),
    ]
