# Generated by Django 4.1.1 on 2023-03-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0013_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='vehicle_details',
            new_name='driverid',
        ),
    ]
