# Generated by Django 4.1.1 on 2023-03-18 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_company_userid'),
        ('Company', '0014_rename_vehicle_details_employee_driverid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(default='1000', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='1', max_length=100)),
                ('companyid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.company')),
            ],
        ),
        migrations.RenameModel(
            old_name='Driver',
            new_name='Driver_offer',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='employee_offer',
            name='driverid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Company.driver_offer'),
        ),
    ]
