# Generated by Django 4.1.1 on 2023-03-18 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_company_userid'),
        ('Company', '0015_employee_offer_rename_driver_driver_offer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(default='1000', max_length=100)),
                ('status', models.CharField(default='1', max_length=100)),
                ('companyid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.company')),
            ],
        ),
    ]
