# Generated by Django 4.1.1 on 2023-03-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0016_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle',
            new_name='vehicle_number',
        ),
    ]
