# Generated by Django 4.1.1 on 2023-03-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0017_rename_vehicle_vehicle_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
