# Generated by Django 4.1.1 on 2023-03-19 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0019_alter_driver_offer_companyid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_offer',
            name='vehicle_details',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Company.vehicle'),
        ),
    ]
