# Generated by Django 4.1.1 on 2023-03-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0020_alter_driver_offer_vehicle_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver_offer',
            old_name='vehicle_details',
            new_name='vehicleid',
        ),
    ]
