# Generated by Django 4.1.1 on 2023-03-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0021_rename_vehicle_details_driver_offer_vehicleid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver_offer',
            old_name='vehicleid',
            new_name='vehicle_details',
        ),
    ]
