# Generated by Django 4.1.1 on 2023-03-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0022_rename_vehicleid_driver_offer_vehicle_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_offer',
            name='vehicle_details',
            field=models.CharField(default='', max_length=100),
        ),
    ]
