# Generated by Django 4.1.1 on 2023-03-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0024_alter_driver_offer_vehicle_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_offer',
            name='license',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
