# Generated by Django 4.1.1 on 2023-03-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0025_driver_offer_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_offer',
            name='license',
        ),
    ]
