# Generated by Django 4.1.1 on 2023-03-28 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_employee_job_application'),
        ('Company', '0026_remove_driver_offer_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_offer',
            name='vehicle_details',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Company.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='companyid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.company'),
        ),
    ]
