# Generated by Django 4.1.1 on 2023-03-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0030_remove_driver_offer_vehicle_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_offer',
            name='vacancy',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='employee_offer',
            name='vacancy',
            field=models.IntegerField(default='1'),
        ),
    ]
