# Generated by Django 4.1.1 on 2023-03-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0031_driver_offer_vacancy_employee_offer_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_offer',
            name='end_time',
            field=models.CharField(default='6:00', max_length=100),
        ),
        migrations.AddField(
            model_name='employee_offer',
            name='start_time',
            field=models.CharField(default='9:00', max_length=100),
        ),
    ]
