# Generated by Django 4.1.1 on 2023-04-03 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0033_dumbster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dumbster',
            old_name='numberofdumbster',
            new_name='number',
        ),
    ]
