# Generated by Django 4.1.1 on 2023-04-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0034_rename_numberofdumbster_dumbster_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumbster',
            name='status',
            field=models.BooleanField(default='1', max_length=100),
        ),
    ]
