# Generated by Django 4.1.1 on 2023-04-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0035_alter_dumbster_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumbster',
            name='perdayrate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
