# Generated by Django 4.1.1 on 2023-04-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0036_dumbster_perdayrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dumbster',
            name='perdayrate',
        ),
    ]
