# Generated by Django 4.1.1 on 2023-04-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0037_remove_dumbster_perdayrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.BooleanField(default='1', max_length=100),
        ),
    ]
